# Generated by Django 3.0.5 on 2021-03-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDjango',
            fields=[
                ('text', models.TextField()),
            ],
        ),
    ]
