# Generated by Django 3.0.5 on 2021-04-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVisualisasiDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_maps_bahagia', models.TextField()),
                ('value_maps_tidakbahagia', models.TextField()),
                ('value_line_bahagia', models.TextField()),
                ('value_line_tidakbahagia', models.TextField()),
                ('data_line', models.TextField()),
                ('value_bar_bahagia', models.TextField()),
                ('value_bar_tidakbahagia', models.TextField()),
                ('data_bar', models.TextField()),
                ('value_pie_bahagia', models.TextField()),
                ('value_pie_tidakbahagia', models.TextField()),
                ('value_card_bahagia', models.TextField()),
                ('value_card_tidakbahagia', models.TextField()),
                ('value_card_total', models.TextField()),
            ],
        ),
    ]
